apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: okgeniecust-app-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/inkredus/argocd-springboot-app-config.git
    targetRevision: argocd-test
    path: argocd
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true